services:
  hadoop:
    image: harisekhon/hadoop
    container_name: hadoop
    hostname: hadoop
    ports:
      - "9870:9870"   # HDFS UI
      - "8088:8088"   # YARN UI
    volumes:
      - ./data:/data:ro      # share your input data
      - ./target:/jar:ro     # share your built JAR
      - ./out:/out           # optional: save output locally
